# Generated by Django 5.1.1 on 2024-09-04 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='journal.student'),
        ),
    ]
