# Generated by Django 5.1.1 on 2024-09-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_exercise_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='user_name',
            field=models.CharField(max_length=64),
        ),
    ]
